services:
  java-api:
    build: ./src/sync_images/pcloud-java
    ports:
      - "8080:8080"
    environment:
      - PCLOUD_USERNAME=${PCLOUD_USERNAME}
      - PCLOUD_PASSWORD=${PCLOUD_PASSWORD}
      - PCLOUD_DOWNLOAD_PATH=/tmp/images
    volumes:
      - /tmp/images:/tmp/images

  frontend:
    build: ./src/frontend
    ports:
      - "8501:8501"
    volumes:
      - /tmp/images:/tmp/images
    environment:
      - BASE_PATH=/tmp/images
    depends_on:
      - java-api

  chromadb:
    build: ./src/vectordb
    ports:
      - "8000:8000"
    volumes:
      - /tmp/images/vectordb:/data

  worker_tags:
    build: ./src/indexing/create_tags
    ports:
      - "50051:50051"
    volumes:
      - /tmp/images:/tmp/images
    environment:
      - CHROMA_HOST=chromadb
    depends_on:
      - chromadb

  worker_thumbnails:
    build: ./src/indexing/create_thumbnails
    ports:
      - "50052:50052"
    volumes:
      - /tmp/images:/tmp/images
      - /tmp/images/thumbnails:/tmp/images/thumbnails

  worker_embeddings:
    build: ./src/indexing/create_embeddings
    deploy:
      replicas: 5
    ports:
      - "50053:50053"
    volumes:
      - /tmp/images:/tmp/images
    environment:
      - CHROMA_HOST=chromadb
    depends_on:
      - chromadb

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    ports:
      - "9090:8080"
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro

volumes:
  images:
  data: