# pcloud login credentials
pcloud.api.username=${PCLOUD_USERNAME:default_username}
pcloud.api.password=${PCLOUD_PASSWORD:default_password}

# storage path for downloaded files
pcloud.download.path=${PCLOUD_DOWNLOAD_PATH:/tmp/images}