syntax = "proto3";

package saga_tags;

// Der gRPC-Service, den jeder der 3 Worker implementieren muss
service WorkerService {
  rpc ProcessTask (TaskRequest) returns (TaskResponse);
}

// Die Anfrage für die Verarbeitung einer Aufgabe
message TaskRequest {
  string task_id = 1;     // Eindeutige ID für die Idempotenz-Prüfung
  string img_path = 2;     // Die eigentlichen Daten (z. B. Datei-Inhalte)
}

// Die Antwort nach erfolgreichem lokalem Commit
message TaskResponse {
  string status = 1;      // COMPLETED, FAILED, oder ALREADY_EXISTS
  string db_record_id = 2; // Die ID des erzeugten Datenbank-Eintrags für das Saga-Log
  string metadata_json = 3;
  repeated float embedding = 4;
  string thumbnail_path = 5;
}

// Der Kompensations-Befehl vom Orchestrator
