# pcloud
pcloud:
  # local path to sync with pcloud drive
  local_path: /home/micmink/data/pcloud_sync

thumbnails:
  # path to store generated thumbnails
  thumbnail_dir: thumbnails
  thumbnail_size: [150, 150] # Max Thumbnail Größe
  max_image_width: 800 # Breite für vergrößertes Bild