[project]
name = "frontend"
version = "0.1.0"
description = "Frontend UI for Pixplore"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "streamlit",
    "pyyaml",
    "Pillow",
    "chromadb==1.5.9",
    "requests",
    "numpy",
    "opentelemetry-distro",
    "opentelemetry-exporter-otlp",
]
