# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""

import grpc

import service_pb2 as service__pb2

GRPC_GENERATED_VERSION = "1.83.0"
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower

    _version_not_supported = first_version_is_lower(
        GRPC_VERSION, GRPC_GENERATED_VERSION
    )
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f"The grpc package installed is at version {GRPC_VERSION},"
        + " but the generated code in service_pb2_grpc.py depends on"
        + f" grpcio>={GRPC_GENERATED_VERSION}."
        + f" Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}"
        + f" or downgrade your generated code using grpcio-tools<={GRPC_VERSION}."
    )


class WorkerServiceStub:
    """Der gRPC-Service, den jeder der 3 Worker implementieren muss"""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ProcessTask = channel.unary_unary(
            "/saga_tags.WorkerService/ProcessTask",
            request_serializer=service__pb2.TaskRequest.SerializeToString,
            response_deserializer=service__pb2.TaskResponse.FromString,
            _registered_method=True,
        )


class WorkerServiceServicer:
    """Der gRPC-Service, den jeder der 3 Worker implementieren muss"""

    def ProcessTask(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_WorkerServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "ProcessTask": grpc.unary_unary_rpc_method_handler(
            servicer.ProcessTask,
            request_deserializer=service__pb2.TaskRequest.FromString,
            response_serializer=service__pb2.TaskResponse.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        "saga_tags.WorkerService", rpc_method_handlers
    )
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers(
        "saga_tags.WorkerService", rpc_method_handlers
    )


# This class is part of an EXPERIMENTAL API.
class WorkerService:
    """Der gRPC-Service, den jeder der 3 Worker implementieren muss"""

    @staticmethod
    def ProcessTask(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/saga_tags.WorkerService/ProcessTask",
            service__pb2.TaskRequest.SerializeToString,
            service__pb2.TaskResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )
